### PR TITLE
Added multi-sources that try to avoid exchange symmetry problem

### PR DESCRIPTION
**Pull request by rbmetcalf**
I am having trouble running these because of an error I do not understand.  I get the following output:

```
metcalf1:examples bmetcalf$ ../bin/lensed --verbose hst_siesh_double.ini 
  _                         _  ___
 | |                       | |/   \
 | | ___ _ __  ___  ___  __| |  A  \  lensed 0.4.0
 | |/ _ \ '_ \/ __|/ _ \/ _` | < > |
 | |  __/ | | \__ \  __/ (_| |  V  /
 |_|\___|_| |_|___/\___|\__,_|\___/ 
                              
options
  gpu = true
  output = true
  root = chains/hst_11602_02_wfc3_uvis_f475w_sci_cut-lens_galaxy-siesh-3
  image = hst_11602_02_wfc3_uvis_f475w_sci_cut.fits
  gain = 5454
  offset = 0
  weight = none
  mask = none
  psf = tt_psf.fits
  nlive = 300
  ins = true
  mmodal = true
  ceff = true
  acc = 0.05
  tol = 0.1
  shf = 0.8
  maxmodes = 100
  updint = 1000
  seed = -1
  resume = false
  maxiter = 0
objects
  sky = sky
  host = sersic
  lens = sie_plus_shear
  source1 = double_sersic
parameters
  1: sky.bg ~ U(0, 0.05)
  2: sky.dx ~ 0
  3: sky.dy ~ 0
  4: host.x ~ 234.955
  5: host.y ~ 236.351
  6: host.r ~ 24.9943
  7: host.mag ~ -4.53667
  8: host.n ~ 2.5621
  9: host.q ~ 0.876609
  10: host.pa ~ 75.9685
  11: lens.x ~ U(220, 250)
  12: lens.y ~ U(220, 250)
  13: lens.r ~ U(120, 140)
  14: lens.q ~ U(0.5, 1)
  15: lens.pa ~ U(0, 180)
  16: lens.g1 ~ U(-1, 1)
  17: lens.g2 ~ U(-1, 1)
  18: source1.x1 ~ U(150, 300)
  19: source1.y1 ~ U(150, 300)
  20: source1.r1 ~ U(0.5, 50)
  21: source1.mag1 ~ U(-10, 0)
  22: source1.n1 ~ U(0.5, 8)
  23: source1.q1 ~ U(0.1, 1)
  24: source1.pa1 ~ U(0, 180)
  25: source1.x2 ~ U(150, 300)
  26: source1.y2 ~ U(150, 300)
  27: source1.r2 ~ U(0.5, 50)
  28: source1.mag2 ~ U(-10, 0)
  29: source1.n2 ~ U(0.5, 8)
  30: source1.q2 ~ U(0.1, 1)
  31: source1.pa2 ~ U(0, 180)
data
  image size: 470 x 470
  image pixels: 220900
  pixel origin: ( 1, 1 )
  pixel scale: ( 1.000000, 1.000000 )
  PSF size: 29 x 29
  background: 0.020085 ± 0.003136
quadrature
  number of points: 49
kernel
  device: ATI Radeon HD 5770
    type: GPU
    vendor: AMD
    version: OpenCL 1.2 
    compiler: OpenCL C 1.2 
    driver: 1.2 (Sep 28 2014 22:27:20)
    units: 10
  load program
  create program
  build program
  block size: 16 x 16
  work size: 480 x 480
  create data buffers
  create quadrature buffers
  create object buffer
  create parameter buffer
  create parameter kernel
  create render buffer
  create render kernel
[CL_INVALID_ARG_SIZE] : OpenCL Error : clSetKernelArg failed: Argument 1 has __constant or __global storage which is only allowed for cl_mem objects.
[CL_INVALID_ARG_INDEX] : OpenCL Error : clSetKernelArg failed: arg_index = 5 is too big. This kernel only has 5 arguments.
error: failed to set render kernel arguments
```

### CODE REVIEW

**Comment by ntessore** [comment]
I'm against putting these into the base distribution of Lensed. If they solve some future problem, we can make them available separately.

**Comment by rbmetcalf** [comment]
That is ok with me for now.  If we had a way of linking parameter priors we could do the same thing.

**Comment by rbmetcalf** [comment]
What kind of a problem?

**Comment by ntessore** [comment]
I'm closing this then, as linking parameters is surely on the horizon.

**Comment by rbmetcalf** [comment]
Lets keep the branch somewhere though.

**Comment by ntessore** [comment]
I restored the branch, we can keep it here.

**Pull request closed without merging**
