### PR TITLE
image plane priors for position

### PR DESCRIPTION
**Pull request by ntessore**
This PR introduces image plane priors for the positions of objects. With these, it's possible to fix the position of a source to one of its visible images. This is done in the ini file by prefixing the prior with `image`, for example

```ini
source.x   = image unif 34 36
source.y   = image unif 63 65
```

The image plane prior is calculated in the `set_params` kernel which is called when parameters need adjustment. Given how rarely that happens relative to the deflection and surface brightness calculations, there should not be any noticeable impact on performance.

The implementation is restricted to objects that have subsequent parameters x and y (i.e. all of the current ones).

### CODE REVIEW

**Comment by ntessore** [comment]
cc @fabiobg83 @rbmetcalf

**Comment by rbmetcalf** [comment]
Excellent!

**Comment by ntessore** [comment]
I'm a bit peeved by the fact that this was possible with so little changes.

**Comment by ntessore** [comment]
There is a problem with the different address spaces used for `data`. The way it's written seems to work on integrated cards, but not on those with dedicated memory.

I think I have to change the storage of the `data` objects to local memory before this can work.

**Comment by ntessore** [comment]
I have rebased this onto the proposed changes of #202 as they should take care of the problems.

**Pull request merged**
